import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Corelink Messaging</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Corelink Messaging
        </h1>

        <p className={styles.description}>
          Click the buttons below to either log in, or sign up.
        </p>

        <div className={styles.grid}>
          <a href="%PUBLIC_URL%/login" className={styles.card}>
            <h2>Log In &rarr;</h2>
            <p>Login to your Corelink server using existing credentials.</p>
          </a>

          <a href="%PUBLIC_URL%/sign-up" className={styles.card}>
            <h2>Sign Up &rarr;</h2>
            <p>Create an account and start messaging.</p>
          </a>
        </div>
      </main>
    </div>
  )
}
